### ISSUE TITLE
[BUG] Error on CPU page, Ubuntu 22.04.

### ISSUE THREAD

**Issue by Morpheus636** [ngxson/hobby-framework-battery#5]
When I go to `localhost:1515/cpu` on Ubuntu 22.04, all I get is an error. The same error appears in the systemd journal. The error is as follows.

```
Error: ENOENT: no such file or directory, open '/sys/fs/cgroup/cpuset/active_cores/cpuset.cpus'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at Object.readFileSync (/usr/sbin/frmw-service:233:55)
    at getHTMLContent (/usr/sbin/bundle.js:37305:10)
    at /usr/sbin/bundle.js:37367:22
    at Layer.handle [as handle_request] (/usr/sbin/bundle.js:11262:5)
    at next (/usr/sbin/bundle.js:11494:13)
    at Route.dispatch (/usr/sbin/bundle.js:11464:3)
    at Layer.handle [as handle_request] (/usr/sbin/bundle.js:11262:5)
    at /usr/sbin/bundle.js:10776:15
```

**Comment by Morpheus636** [comment]
Update: looks like a relatively simple fix, `install.sh` should check if `/sys/fs/cgroup/cpuset/active_cores` exists, and use `mkdir` to create it if not. 

Similarly, `uninstall.sh` should use `rmdir` to remove that same directory.

**Comment by ngxson** [comment]
Hi! Can you verify if the directory `/sys/fs/cgroup/cpuset/active_cores` exists? Can you also do a `ls` to see what's inside?
Thanks!

**Comment by Morpheus636** [comment]
The error is correct, the directory does not exist.

**Comment by sniff122** [comment]
also running 22.04 with this exact issue

**Comment by ngxson** [comment]
@Morpheus636 @sniff122 Sorry for the `unsigned long long` delay. Can you please run these command as `sudo` to see if it works? These command creates a cgroup for current active cores:

```
mkdir /sys/fs/cgroup/cpuset;
mount -t cgroup -o cpuset cpuset /sys/fs/cgroup/cpuset;
cgcreate -g cpuset:active_cores;
```
