### ISSUE TITLE
CPU Tuning Save and Apply

### ISSUE THREAD

**Issue by josh1244** [ngxson/hobby-framework-battery#7]
When I try to apply any of the CPU tuning it gives me:

TypeError: Cannot read property 'toString' of undefined
    at /usr/sbin/bundle.js:37381:40
    at Layer.handle [as handle_request] (/usr/sbin/bundle.js:11262:5)
    at next (/usr/sbin/bundle.js:11494:13)
    at Route.dispatch (/usr/sbin/bundle.js:11464:3)
    at Layer.handle [as handle_request] (/usr/sbin/bundle.js:11262:5)
    at /usr/sbin/bundle.js:10776:15
    at Function.process_params (/usr/sbin/bundle.js:10838:12)
    at next (/usr/sbin/bundle.js:10772:10)
    at sendHtmlBodyMiddleware (/usr/sbin/bundle.js:37951:5)
    at Layer.handle [as handle_request] (/usr/sbin/bundle.js:11262:5)

I can use the force buttons. They seem to work fine,.

------------------------Intel 11th Gen------------------
{
  "cpu": {},
  "ectool": {
    "chargingLimitEnd": 100,
    "isChargingPaused": false,
    "keyRemaps": []
  }
}

-------------
More information:
CPU

{
  "name": "11th Gen Intel",
  "regex": {},
  "pCores": null,
  "eCores": null,
  "allCores": null,
  "lowPowerCores": null,
  "powerLimitsBattery": {
    "PL1": 8,
    "PL2": 20
  },
  "powerLimitsAC": {
    "PL1": 40,
    "PL2": 65
  },
  "autoPowerLimit": false,
  "autoCoreLimit": false
}

**Comment by ngxson** [comment]
Hello, sorry for the `unsigned long long` delay. I try to fix the problem on this commit: https://github.com/ngxson/hobby-framework-battery/commit/1eba0f1eb653688d77379cee184b2de4d310d687

Please let me know if it works. Thanks!
